DROP TABLE IF EXISTS players, teams;

CREATE TABLE players (
    id SERIAL PRIMARY KEY,
    name TEXT,
    full_name TEXT,
    birth_date DATE,
    age INTEGER,
    height_cm NUMERIC,
    weight_kgs NUMERIC,
    positions TEXT,
    nationality TEXT,
    overall_rating INTEGER,
    potential INTEGER,
    value_euro NUMERIC,
    wage_euro NUMERIC,
    preferred_foot TEXT,
    international_reputation INTEGER CHECK (international_reputation BETWEEN 1 AND 5),
    weak_foot INTEGER CHECK (weak_foot BETWEEN 1 AND 5),
    skill_moves INTEGER CHECK (skill_moves BETWEEN 1 AND 5),
    body_type TEXT,
    release_clause_euro NUMERIC,
    national_team TEXT,
    national_rating INTEGER,
    national_team_position TEXT,
    national_jersey_number INTEGER,
    crossing INTEGER,
    finishing INTEGER,
    heading_accuracy INTEGER,
    short_passing INTEGER,
    volleys INTEGER,
    dribbling INTEGER,
    curve INTEGER,
    freekick_accuracy INTEGER,
    long_passing INTEGER,
    ball_control INTEGER,
    acceleration INTEGER,
    sprint_speed INTEGER,
    agility INTEGER,
    reactions INTEGER,
    balance INTEGER,
    shot_power INTEGER,
    jumping INTEGER,
    stamina INTEGER,
    strength INTEGER,
    long_shots INTEGER,
    aggression INTEGER,
    interceptions INTEGER,
    positioning INTEGER,
    vision INTEGER,
    penalties INTEGER,
    composure INTEGER,
    marking INTEGER,
    standing_tackle INTEGER,
    sliding_tackle INTEGER
);